name: coding & stuff
url: http://grossjonas.github.io
description: ... just some place to store notes on coding, devops, admin and other stuff

markdown: kramdown
highlighter: rouge
lsi: false
paginate: 5

exclude: [vendor, 'README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins: ['jekyll-feed', 'jekyll-paginate']
