name: coding & stuff
url: http://grossjonas.github.io
description: ... just some place to store coding notes and stuff

markdown: kramdown
highlighter: rouge
safe: true
lsi: false
paginate: 5

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

gems:
    - jekyll-feed
    - jekyll-paginate
