name: coding & stuff
url: http://grossjonas.github.io
description: ... just some place to store notes on coding, devops, admin and other stuff

markdown: kramdown
highlighter: rouge
safe: true
lsi: false
paginate: 5

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

kramdown:
  input: GFM
  syntax_highlighter: rouge

gems:
    - jekyll-feed
    - jekyll-paginate
